### ISSUE TITLE
Cant install py-chenhancc package

### ISSUE THREAD

**Issue by Dado87** [aalavandhaann/chenhan_cython#1]
Python Version: 3.8.2

**Environment:**
Package    Version
autowrap   0.22.0
Cython     0.29.16
numpy      1.18.3
pip        20.0.2
setuptools 41.2.0

**Error at "pip install py-chenhancc" :**
```
Collecting py-chenhancc
  Using cached py_chenhancc-0.0.3.tar.gz (114 kB)
Requirement already satisfied: autowrap in c:\users\dk\documents\py_projekti\geodetka\venv\lib\site-packages (from py-chenhancc) (0.22.0)
Requirement already satisfied: Cython>=0.19 in c:\users\dk\documents\py_projekti\geodetka\venv\lib\site-packages (from autowrap->py-chenhancc) (0.29.16)
Installing collected packages: py-chenhancc
    Running setup.py install for py-chenhancc ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\dk\documents\py_projekti\geodetka\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dk\\AppData\\Local\\Temp\\pip-install-pwvvae1j\\py-chenhancc\\setup.py'"'"'; __file__='"'"'C:\\Users\\dk\\AppData\\Local\\Temp\\pip-install-pwvvae1j\\py-chenhancc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\dk\AppData\Local\Temp\pip-record-ejgi8eiv\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\dk\documents\py_projekti\geodetka\venv\include\site\python3.8\py-chenhancc'
         cwd: C:\Users\dk\AppData\Local\Temp\pip-install-pwvvae1j\py-chenhancc\
    Complete output (53 lines):
    running install
    running build
    running build_ext
    building 'py_chenhancc' extension
    creating build
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\dk\documents\py_projekti\geodetka\venv\lib\site-packages\autowrap\data_files\autowrap -Ic:\users\dk\documents\py_projekti\geodetka\venv\lib\site-packages\autowrap\data_files -Ic:\users\dk\documents\py_projekti\geodetka\venv\include -IC:\Users\dk\AppData\Local\Programs\Python\Python38\include -IC:\Users\dk\AppData\Local\Programs\Python\Python38\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpsrc/py_chenhancc.cpp /Fobuild\temp.win-amd64-3.8\Release\src/py_chenhancc.obj -std=c++14
    cl : Command line warning D9002 : ignoring unknown option '-std=c++14'
    py_chenhancc.cpp
    C:\Users\dk\AppData\Local\Temp\pip-install-pwvvae1j\py-chenhancc\src\ICHWithFurtherPriorityQueue.hpp(189): warning C4244: '=': conversion from 'unsigned __int64' to 'double', possible loss of data
    src/py_chenhancc.cpp(21916): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(21921): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(21936): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(21951): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(21956): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(21961): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(21976): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(21991): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22006): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22021): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22026): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22029): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22032): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22035): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22038): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22041): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22044): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22047): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22050): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22053): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22056): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22059): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22062): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22065): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22068): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22071): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22074): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(22077): warning C4996: '_typeobject::tp_print': deprecated in 3.8
    src/py_chenhancc.cpp(23608): error C2039: 'exc_type': is not a member of '_ts'
    C:\Users\dk\AppData\Local\Programs\Python\Python38\include\cpython/pystate.h(51): note: see declaration of '_ts'
    src/py_chenhancc.cpp(23609): error C2039: 'exc_value': is not a member of '_ts'
    C:\Users\dk\AppData\Local\Programs\Python\Python38\include\cpython/pystate.h(51): note: see declaration of '_ts'
    src/py_chenhancc.cpp(23610): error C2039: 'exc_traceback': is not a member of '_ts'
    C:\Users\dk\AppData\Local\Programs\Python\Python38\include\cpython/pystate.h(51): note: see declaration of '_ts'
    src/py_chenhancc.cpp(23611): error C2039: 'exc_type': is not a member of '_ts'
    C:\Users\dk\AppData\Local\Programs\Python\Python38\include\cpython/pystate.h(51): note: see declaration of '_ts'
    src/py_chenhancc.cpp(23612): error C2039: 'exc_value': is not a member of '_ts'
    C:\Users\dk\AppData\Local\Programs\Python\Python38\include\cpython/pystate.h(51): note: see declaration of '_ts'
    src/py_chenhancc.cpp(23613): error C2039: 'exc_traceback': is not a member of '_ts'
    C:\Users\dk\AppData\Local\Programs\Python\Python38\include\cpython/pystate.h(51): note: see declaration of '_ts'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\dk\documents\py_projekti\geodetka\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dk\\AppData\\Local\\Temp\\pip-install-pwvvae1j\\py-chenhancc\\setup.py'"'"'; __file__='"'"'C:\\Users\\dk\\AppData\\Local\\Temp\\pip-install-pwvvae1j\\py-chenhancc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\dk\AppData\Local\Temp\pip-record-ejgi8eiv\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\dk\documents\py_projekti\geodetka\venv\include\site\python3.8\py-chenhancc' Check the logs for full command output.
```

There should be some issue with with c++ 14
( Command line warning D9002 : ignoring unknown option '-std=c++14' )

Maybe something like this?
[https://github.com/tensorflow/tensorflow/issues/33618]

Any suggestion how to solve it?
Regards,
Dado

**Comment by aalavandhaann** [comment]
Can you please inform what operating system is used here? Is it Anaconda environment? Please provide the system details as well. I will try to test on my end

**Comment by Dado87** [comment]
Windows 10 64bit
I used just basic python environment in command prompt (not Anaconda), but using conda environment I get same error.

**Comment by aalavandhaann** [comment]
Hi,

Can you try `pip install py_chenhancc --no-cache-dir` now? Looks like the compiled files `py_chenhancc` and `py_chenhancc.cpp` are not working with newer version of **cython**. Hence it is necessary to recompile these files using **autowrap**. I have updated `setup.py` to compile these files on the fly and then proceed to compiling the library. So you have two options

1. Use `pip install py_chenhancc --no-cache-dir`.  The option `--no-cache-dir` is to ensure you download the latest pip package `0.0.5`
2. Otherwise use `python setup.py build_ext` and then do `python setup.py install`. The first commands builds the library and the second command installs the built library

Let me know if you still have any issues.

Regards,
#0K

**Comment by Dado87** [comment]
Installation is now successful in python 3 environment (also in conda venv)! 
Great work, thanks.

Because of same dependencies would need to run the modul in python 2 environment on conda, but there was installation not successful (see attached error below).  

Is modul compatible for python 2?
If yes, can you help me to solve it too?

**Environment:**
 
autowrap                  0.20.0                    
ca-certificates           2020.1.1                   
certifi                   2019.11.28               
cython                    0.29.14          
intel-openmp              2020.0                     
libblas                   3.8.0                    
libcblas                  3.8.0                    
liblapack                 3.8.0                   
mkl                       2020.0             
numpy                     1.15.4       
pip                       19.3.1           
python                    2.7.18         
setuptools                44.0.0             
sqlite                    3.30.1        
vc                        9       
vs2008_runtime            9.00.30729.1  
wheel                     0.33.6 
wincertstore              0.2

**Error:**
[error.txt](https://github.com/aalavandhaann/chenhan_cython/files/4535203/error.txt)

**Comment by aalavandhaann** [comment]
I believe the error is coming from VC9 but I am not sure. Can you try increasing the VC version to the latest but using Python2? Let me know how that goes

Regards,
#0K

**Comment by Dado87** [comment]
hm...

![image](https://user-images.githubusercontent.com/11155948/80316603-00ea8080-87ff-11ea-882c-4c82e3a432e8.png)

source: [https://wiki.python.org/moin/WindowsCompilers]

**Comment by aalavandhaann** [comment]
Hello Dado,

I investigate on Windows 10 and using VC9 for python2.7 all with Anaconda environment. I am getting the same issues. However, I tried to compile for python 2.7 in Ubuntu 18.04 and found no issues (tested using `pip install py-chenhancc`). 

The issues that you pointed out is about how the vectors are iterated. Looks like VC 9 does not like range iteration of vectors and hence I changed the code to iterate over the vectors for vertices and faces using the classic way(using `(for int i=0;i<vertices.size();i++`). This way the errors disappeared. But still I was not able to compile the python2 library on windows and the errors were are as shown below,

```
C:\Users\ashok\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\ashok\anaconda3\envs\py2\lib\site-packages\autowrap\data_files\autowrap -IC:\Users\ashok\anaconda3\envs\py2\lib\site-packages\autowrap\data_files -IC:\Users\ashok\anaconda3\envs\py2\include -IC:\Users\ashok\anaconda3\envs\py2\PC /Tpsrc/py_chenhancc.cpp /Fobuild\temp.win-amd64-2.7\Release\src/py_chenhancc.obj -std=c++14
py_chenhancc.cpp
C:\Users\ashok\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\xlocale(342) : warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
c:\users\ashok\downloads\chenhan_cython-master\chenhan_cython-master\src\ICHWithFurtherPriorityQueue.hpp(189) : warning C4244: '=' : conversion from 'unsigned __int64' to 'double', possible loss of data
src/py_chenhancc.cpp(11497) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
src/py_chenhancc.cpp(16167) : warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)
C:\Users\ashok\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Users\ashok\anaconda3\envs\py2\libs /LIBPATH:C:\Users\ashok\anaconda3\envs\py2\PCbuild\amd64 /LIBPATH:C:\Users\ashok\anaconda3\envs\py2\PC\VS9.0\amd64 /EXPORT:initpy_chenhancc build\temp.win-amd64-2.7\Release\src/py_chenhancc.obj /OUT:C:\Users\ashok\Downloads\chenhan_cython-master\chenhan_cython-master\py_chenhancc.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\src\py_chenhancc.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\src\py_chenhancc.pyd.manifest -std=c++14
LINK : warning LNK4044: unrecognized option '/std=c++14'; ignored
py_chenhancc.obj : warning LNK4197: export 'initpy_chenhancc' specified multiple times; using first specification
   Creating library build\temp.win-amd64-2.7\Release\src\py_chenhancc.lib and object build\temp.win-amd64-2.7\Release\src\py_chenhancc.exp
py_chenhancc.obj : error LNK2019: unresolved external symbol "void __cdecl boost::throw_exception(class std::exception const &)" (?throw_exception@boost@@YAXAEBVexception@std@@@Z) referenced in function "struct _object * __cdecl __pyx_pf_12py_chenhancc_24CImprovedCHWithEdgeValve_2GetVertexDistances(struct __pyx_obj_12py_chenhancc_CImprovedCHWithEdgeValve *)" (?__pyx_pf_12py_chenhancc_24CImprovedCHWithEdgeValve_2GetVertexDistances@@YAPEAU_object@@PEAU__pyx_obj_12py_chenhancc_CImprovedCHWithEdgeValve@@@Z)
C:\Users\ashok\Downloads\chenhan_cython-master\chenhan_cython-master\py_chenhancc.pyd : fatal error LNK1120: 1 unresolved externals

error: command 'C:\\Users\\ashok\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1120
```

The whole seems to be something related to boost library and VC9. I am afraid that it is not possible to support python 2 for windows. Also the life of python2.7 is reaching its end and hence I do not see any point to invest time into this. If you feel this could be solved then I would be happy to do a PR. However, I am going to close this issue as it has been solved for the original issue of python 3.

Regards,
#0K

**Comment by Dado87** [comment]
Hi,

as already stated modul py_chenhancc was installed
 to my conda environment
[image: image.png]

but when I run "import py_chenhancc" or for example your test.py,
I get Error: No module

[image: image.png]

What I'm doing wrong? Or ist there issue with module?


V V ned., 26. apr. 2020 ob 21:41 je oseba #0K Srinivasan Ramachandran <
notifications@github.com> napisala:

**Comment by aalavandhaann** [comment]
I tried on both Ubuntu 18.04 with Python 3.6 and Windows 10 with Anaconda Python 3.7 and it works fine for me. As far as I know if the module installed fine then it should work fine. Also I am not able to see your image attachments. 

Regards,
#0K

**Comment by Dado87** [comment]
I had before version 0.0.5, after new installation of version 0.0.7 not it
works.

Do you have any example with larger mesh where you import faces, vertices,
source pt, target pt and get out geodesic path?

**Comment by aalavandhaann** [comment]
Hi,

I usually create python libraries to be used with Blender and this too was such an attempt. See [this](https://github.com/aalavandhaann/ch_bl_geodesics) repository for how to use the geodesic path algorithm with Blender. The repository contains a Blender plugin that will check if this geodesic library is installed, otherwise, it will use the pure python implementation of the same geodesic algorithm that is 210x slower than py-chenhancc. But it does the job. So if you install the Blender plugin then you don't have to worry about importing meshes and handling their mesh data. All that is done in Blender by the plugin itself. 

If you are not sure how to install python libraries for the python inside a standalone Blender environment  then look into [this](http://hash0k.com/blender-bundled-python-tricks/). 

In case you run into some trouble when importing `sklearn` library refer to this [url](http://hash0k.com/python-blender-import-sklearn/) on how to fix the issue (Hope you don't run into this error)
